# Generated by Django 3.0.6 on 2020-10-19 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coursemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='semestermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='subjectmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(max_length=50)),
                ('coursename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coursemodel')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.semestermodel')),
            ],
        ),
        migrations.CreateModel(
            name='usermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('enrollment', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=12)),
                ('batch', models.CharField(max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coursemodel')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.semestermodel')),
            ],
            options={
                'ordering': ['enrollment'],
            },
        ),
        migrations.CreateModel(
            name='teammodel',
            fields=[
                ('team_no', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('topic_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('student', models.ManyToManyField(to='app.usermodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subjectmodel')),
            ],
        ),
    ]
