# Generated by Django 3.0.6 on 2020-09-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mscitmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('enrollment', models.IntegerField()),
                ('semester', models.CharField(choices=[('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='7', max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=12)),
                ('batch', models.CharField(max_length=10)),
                ('course', models.CharField(choices=[('imscit', 'Imscit'), ('mscit', 'Mscit'), ('pgdca', 'Pgdca')], default='mscit', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='pgdcamodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('enrollment', models.IntegerField()),
                ('semester', models.CharField(choices=[('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='7', max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=12)),
                ('batch', models.CharField(max_length=10)),
                ('course', models.CharField(choices=[('imscit', 'Imscit'), ('mscit', 'Mscit'), ('pgdca', 'Pgdca')], default='pgdca', max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='usermodel',
            new_name='imscitmodel',
        ),
    ]
