# Generated by Django 3.0.6 on 2020-10-31 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200923_1709'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='imscitmodel',
            new_name='usermodel',
        ),
        migrations.DeleteModel(
            name='mscitmodel',
        ),
        migrations.DeleteModel(
            name='pgdcamodel',
        ),
    ]
